"""Initial migration

Revision ID: 82262fdcc2c5
Revises: 
Create Date: 2026-02-17 00:11:08.112172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82262fdcc2c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('entry', 'work', 'pro', name='levelenum'), nullable=False),
    sa.Column('subject', sa.Enum('algorithm', 'language', 'standard', 'design', name='subjectenum'), nullable=False),
    sa.Column('type', sa.Enum('single', 'multiple', 'judge', 'subjective', name='typeenum'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('default_level', sa.Enum('entry', 'work', 'pro', name='levelenum'), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_index(op.f('ix_users_ip'), 'users', ['ip'], unique=False)
    op.create_table('answer_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ip', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('exam_session', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_ip'], ['users.ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_records_id'), 'answer_records', ['id'], unique=False)
    op.create_table('wrong_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ip', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.Column('mastered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_ip'], ['users.ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrong_book_id'), 'wrong_book', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wrong_book_id'), table_name='wrong_book')
    op.drop_table('wrong_book')
    op.drop_index(op.f('ix_answer_records_id'), table_name='answer_records')
    op.drop_table('answer_records')
    op.drop_index(op.f('ix_users_ip'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
